// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package download

import (
	"aurora-file-sharing/api/download"
)

type ControllerV1 struct{}

func NewV1() download.IDownloadV1 {
	return &ControllerV1{}
}
