// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file_list

import (
	"aurora-file-sharing/api/file_list"
)

type ControllerV1 struct{}

func NewV1() file_list.IFileListV1 {
	return &ControllerV1{}
}
