// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file_list

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/google/uuid"
)

var (
	uploadDir      = "upload"
	uploadFileName = ""
)

func GenerateRandomID() string {
	return uuid.New().String()
}

func FileUpload(r *ghttp.Request) {
	file := r.GetUploadFile("file")
	if file == nil {
		r.Response.Write("file is nil")
		r.Response.WriteJson(
			g.Map{
				"code":    400,
				"message": "文件为空",
			},
		)
		return
	}

	fileName, err := file.Save(uploadDir)
	if err != nil {
		uploadFileName = ""
		r.Response.Write("upload failed")
		r.Response.WriteJson(
			g.Map{
				"code":    500,
				"message": "文件上传失败",
			},
		)
	}

	uploadFileName = fileName
	r.Response.WriteJson(
		g.Map{
			"code":    200,
			"message": "文件上传成功",
			"data":    fileName,
		},
	)
}
