// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aurora-file-sharing/internal/dao/internal"
)

// fileListDao is the data access object for the table file_list.
// You can define custom methods on it to extend its functionality as needed.
type fileListDao struct {
	*internal.FileListDao
}

var (
	// FileList is a globally accessible object for table file_list operations.
	FileList = fileListDao{internal.NewFileListDao()}
)

// Add your custom methods and functionality below.
