// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aurora-file-sharing/internal/dao/internal"
	"context"
	"database/sql"

	"github.com/gogf/gf/v2/database/gdb"
)

// fileListDao is the data access object for the table file_list.
// You can define custom methods on it to extend its functionality as needed.
type fileListDao struct {
	*internal.FileListDao
}

var (
	// FileList is a globally accessible object for table file_list operations.
	FileList = fileListDao{internal.NewFileListDao()}
)

func (d *fileListDao) InsertAndGetId(ctx context.Context, data map[string]any) (res int64, err error) {
	res, err = d.Ctx(ctx).Data(data).InsertAndGetId()
	if err != nil {
		return 0, err
	}
	return
}

func (d *fileListDao) UpdateByFileName(ctx context.Context, fileName string, data map[string]any) (res sql.Result, err error) {
	res, err = d.Ctx(ctx).Data(data).Where("file_name = ?", fileName).Update()
	if err != nil {
		return nil, err
	}
	if _, err = res.RowsAffected(); err != nil {
		return nil, err
	}
	return
}

// Add your custom methods and functionality below.
func (d *fileListDao) HasExistFileName(ctx context.Context, fileName string) (res gdb.Record, err error) {
	res, err = d.Ctx(ctx).Where("file_name = ?", fileName).One()
	if err != nil {
		return nil, err
	}
	return

}
