// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aurora-file-sharing/internal/dao/internal"
	"context"

	"database/sql"

	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
)

// fileTagRelationDao is the data access object for the table file_tag_relation.
// You can define custom methods on it to extend its functionality as needed.
type fileTagRelationDao struct {
	*internal.FileTagRelationDao
}

var (
	// FileTagRelation is a globally accessible object for table file_tag_relation operations.
	FileTagRelation = fileTagRelationDao{internal.NewFileTagRelationDao()}
)

// Add your custom methods and functionality below.
func (d *fileTagRelationDao) Create(ctx context.Context, fileId string, tagId string) (res sql.Result, err error) {
	if fileId == "" || tagId == "" {
		return nil, gerror.New("fileId和tagId不能为空")
	}
	data := g.Map{
		"file_id": fileId,
		"tag_id":  tagId,
	}
	res, err = d.Ctx(ctx).Data(data).Insert()
	if err != nil {
		return nil, err
	}
	return
}

// 删除
func (d *fileTagRelationDao) Delete(ctx context.Context, fileId string, tagId string) (res sql.Result, err error) {
	if fileId == "" || tagId == "" {
		return nil, gerror.New("fileId和tagId不能为空")
	}
	res, err = d.Ctx(ctx).Where("file_id = ? AND tag_id = ?", fileId, tagId).Delete()
	if err != nil {
		return nil, err
	}
	if rowsAffected, _ := res.RowsAffected(); rowsAffected == 0 {
		return nil, gerror.New("fileId和tagId没有绑定! 无法解绑")
	}
	return
}
