// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aurora-file-sharing/internal/dao/internal"
)

// fileTagRelationDao is the data access object for the table file_tag_relation.
// You can define custom methods on it to extend its functionality as needed.
type fileTagRelationDao struct {
	*internal.FileTagRelationDao
}

var (
	// FileTagRelation is a globally accessible object for table file_tag_relation operations.
	FileTagRelation = fileTagRelationDao{internal.NewFileTagRelationDao()}
)

// Add your custom methods and functionality below.
