// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	v1 "aurora-file-sharing/api/tags/v1"
	"aurora-file-sharing/internal/dao/internal"

	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// tagsDao is the data access object for the table tags.
// You can define custom methods on it to extend its functionality as needed.
type tagsDao struct {
	*internal.TagsDao
}

var (
	// Tags is a globally accessible object for table tags operations.
	Tags = tagsDao{internal.NewTagsDao()}
)

// Add your custom methods and functionality below.
// 通用数据库查询
func (d *tagsDao) Query(ctx context.Context, data *v1.TagsReq) (res *gdb.Model) {
	res = d.Ctx(ctx)
	if data.TagId != "" {
		res = res.Where("tag_id = ?", data.TagId)
	}
	if data.TagName != "" {
		res = res.Where("tag_name like ?", "%"+data.TagName+"%")
	}
	res = res.Limit(data.PageSize, (data.Page-1)*data.PageSize)
	return
}

func (d *tagsDao) QueryByTagId(ctx context.Context, tagId string) (res gdb.Record, err error) {
	res, err = d.Ctx(ctx).Where("tag_id = ?", tagId).One()
	if err != nil {
		return nil, err
	}
	return
}
