// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file_tag_relation

import (
	"aurora-file-sharing/api/file_tag_relation"
)

type ControllerV1 struct{}

func NewV1() file_tag_relation.IFileTagRelationV1 {
	return &ControllerV1{}
}
